# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:title
relative_permalinks: true

# Setup
title:            sunpech.blog
tagline:          'A blog about technology, photography, and stuff.'
description:      'A blog about technology, photography, and stuff.'
url:              http://sunpech.com
homeurl:          /
baseurl:          ""

author:
  name:           'Steven Suwatanapongched'
  url:            https://twitter.com/sunpech

paginate:         1

timezone: "America/Chicago"

sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/index.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

gems:
  - jekyll-redirect-from
  - jekyll-auto-image
  - jekyll-sitemap

# StartBootstrap Clean-Blog Settings
header-img: /public/images/header_LA_home_office.jpg
twitter_username: sunpech
github_username:  sunpech
gplus_username: StevenSuwatanapongched
facebook_username:  SunpechPhotography
instagram_username: sunpechphoto
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
