# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            sunpech.blog
tagline:          'A blog about technology, photography, and stuff.'
description:      'A blog about technology, photography, and stuff.'
url:              http://sunpech.github.io
baseurl:          /

author:
  name:           'Steven Suwatanapongched'
  url:            https://twitter.com/sunpech

paginate:         1

pages_list:       
  About: '/about'
  Contact: '/contact'
  Archive: '/archive'
  Feed: '/atom.xml'

# Custom vars
