# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:title
relative_permalinks: true

# Setup
title:            sunpech.blog
tagline:          'A blog about technology, photography, and stuff.'
description:      'A blog about technology, photography, and stuff.'
url:              http://sunpech.com
baseurl:          /

author:
  name:           'Steven Suwatanapongched'
  url:            https://twitter.com/sunpech

paginate:         1

timezone: "America/Chicago"

gems:
  - jekyll-redirect-from
  - jekyll-auto-image

# Custom vars
